package bean;
// Generated 08/10/2025 16:50:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JatClientes generated by hbm2java
 */
@Entity
@Table(name="jat_clientes"
    ,catalog="db_joao_viana"
)
public class JatClientes  implements java.io.Serializable {


     private int jatIdClientes;
     private String jatNome;
     private String jatApelido;
     private String jatCpf;
     private String jatSenha;
     private String jatTelefone;
     private Date jatDataDeNascimento;
     private String jatEmail;
     private String jatEndereco;
     private String jatBairro;
     private String jatCidade;
     private String jatCep;
     private int jatNivel;
     private String jatAtivo;
     private Date jatDataCadastro;
 

    public JatClientes() {
    }

	
    public JatClientes(int jatIdClientes) {
        this.jatIdClientes = jatIdClientes;
    }
    public JatClientes(int jatIdClientes, String jatNome, String jatApelido, String jatCpf, String jatSenha, String jatTelefone, Date jatDataDeNascimento, String jatEmail, String jatEndereco, String jatBairro, String jatCidade, String jatCep, int jatNivel, String jatAtivo, Date jatDataCadastro, Set jatVendases) {
       this.jatIdClientes = jatIdClientes;
       this.jatNome = jatNome;
       this.jatApelido = jatApelido;
       this.jatCpf = jatCpf;
       this.jatSenha = jatSenha;
       this.jatTelefone = jatTelefone;
       this.jatDataDeNascimento = jatDataDeNascimento;
       this.jatEmail = jatEmail;
       this.jatEndereco = jatEndereco;
       this.jatBairro = jatBairro;
       this.jatCidade = jatCidade;
       this.jatCep = jatCep;
       this.jatNivel = jatNivel;
       this.jatAtivo = jatAtivo;
       this.jatDataCadastro = jatDataCadastro;
     
    }
   
     @Id 

    
    @Column(name="jat_id_clientes", unique=true, nullable=false)
    public int getJatIdClientes() {
        return this.jatIdClientes;
    }
    
    public void setJatIdClientes(int jatIdClientes) {
        this.jatIdClientes = jatIdClientes;
    }

    
    @Column(name="jat_nome", length=80)
    public String getJatNome() {
        return this.jatNome;
    }
    
    public void setJatNome(String jatNome) {
        this.jatNome = jatNome;
    }

    
    @Column(name="jat_apelido", length=30)
    public String getJatApelido() {
        return this.jatApelido;
    }
    
    public void setJatApelido(String jatApelido) {
        this.jatApelido = jatApelido;
    }

    
    @Column(name="jat_cpf", length=14)
    public String getJatCpf() {
        return this.jatCpf;
    }
    
    public void setJatCpf(String jatCpf) {
        this.jatCpf = jatCpf;
    }

    
    @Column(name="jat_senha", length=15)
    public String getJatSenha() {
        return this.jatSenha;
    }
    
    public void setJatSenha(String jatSenha) {
        this.jatSenha = jatSenha;
    }

    
    @Column(name="jat_telefone", length=11)
    public String getJatTelefone() {
        return this.jatTelefone;
    }
    
    public void setJatTelefone(String jatTelefone) {
        this.jatTelefone = jatTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_dataDeNascimento", length=10)
    public Date getJatDataDeNascimento() {
        return this.jatDataDeNascimento;
    }
    
    public void setJatDataDeNascimento(Date jatDataDeNascimento) {
        this.jatDataDeNascimento = jatDataDeNascimento;
    }

    
    @Column(name="jat_email", length=80)
    public String getJatEmail() {
        return this.jatEmail;
    }
    
    public void setJatEmail(String jatEmail) {
        this.jatEmail = jatEmail;
    }

    
    @Column(name="jat_endereco", length=50)
    public String getJatEndereco() {
        return this.jatEndereco;
    }
    
    public void setJatEndereco(String jatEndereco) {
        this.jatEndereco = jatEndereco;
    }

    
    @Column(name="jat_bairro", length=30)
    public String getJatBairro() {
        return this.jatBairro;
    }
    
    public void setJatBairro(String jatBairro) {
        this.jatBairro = jatBairro;
    }

    
    @Column(name="jat_cidade", length=20)
    public String getJatCidade() {
        return this.jatCidade;
    }
    
    public void setJatCidade(String jatCidade) {
        this.jatCidade = jatCidade;
    }

    
    @Column(name="jat_cep", length=10)
    public String getJatCep() {
        return this.jatCep;
    }
    
    public void setJatCep(String jatCep) {
        this.jatCep = jatCep;
    }

    
    @Column(name="jat_nivel", length=15)
    public int getJatNivel() {
        return this.jatNivel;
    }
    
    public void setJatNivel(int jatNivel) {
        this.jatNivel = jatNivel;
    }

    
    @Column(name="jat_ativo", length=1)
    public String getJatAtivo() {
        return this.jatAtivo;
    }
    
    public void setJatAtivo(String jatAtivo) {
        this.jatAtivo = jatAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_dataCadastro", length=10)
    public Date getJatDataCadastro() {
        return this.jatDataCadastro;
    }
    
    public void setJatDataCadastro(Date jatDataCadastro) {
        this.jatDataCadastro = jatDataCadastro;
    }

}


