package bean;
// Generated 08/10/2025 16:50:28 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JatFuncionarios generated by hbm2java
 */
@Entity
@Table(name="jat_funcionarios"
    ,catalog="db_joao_viana"
)
public class JatFuncionarios  implements java.io.Serializable {


     private int jatIdFuncionario;
     private String jatNome;
     private String jatTelefone;
     private String jatCpf;
     private String jatTurno;
     private double jatSalario;
     private String jatEndereco;

    public JatFuncionarios() {
    }

	
    public JatFuncionarios(int jatIdFuncionario) {
        this.jatIdFuncionario = jatIdFuncionario;
    }
    public JatFuncionarios(int jatIdFuncionario, String jatNome, String jatTelefone, String jatCpf, String jatTurno, double jatSalario, String jatEndereco) {
       this.jatIdFuncionario = jatIdFuncionario;
       this.jatNome = jatNome;
       this.jatTelefone = jatTelefone;
       this.jatCpf = jatCpf;
       this.jatTurno = jatTurno;
       this.jatSalario = jatSalario;
       this.jatEndereco = jatEndereco;
    }
   
     @Id 

    
    @Column(name="jat_id_funcionario", unique=true, nullable=false)
    public int getJatIdFuncionario() {
        return this.jatIdFuncionario;
    }
    
    public void setJatIdFuncionario(int jatIdFuncionario) {
        this.jatIdFuncionario = jatIdFuncionario;
    }

    
    @Column(name="jat_nome", length=50)
    public String getJatNome() {
        return this.jatNome;
    }
    
    public void setJatNome(String jatNome) {
        this.jatNome = jatNome;
    }

    
    @Column(name="jat_telefone", length=11)
    public String getJatTelefone() {
        return this.jatTelefone;
    }
    
    public void setJatTelefone(String jatTelefone) {
        this.jatTelefone = jatTelefone;
    }

    
    @Column(name="jat_cpf", length=14)
    public String getJatCpf() {
        return this.jatCpf;
    }
    
    public void setJatCpf(String jatCpf) {
        this.jatCpf = jatCpf;
    }

    
    @Column(name="jat_turno", length=10)
    public String getJatTurno() {
        return this.jatTurno;
    }
    
    public void setJatTurno(String jatTurno) {
        this.jatTurno = jatTurno;
    }

    
    @Column(name="jat_salario", precision=7)
    public double getJatSalario() {
        return this.jatSalario;
    }
    
    public void setJatSalario(double jatSalario) {
        this.jatSalario = jatSalario;
    }

    
    @Column(name="jat_endereco", length=50)
    public String getJatEndereco() {
        return this.jatEndereco;
    }
    
    public void setJatEndereco(String jatEndereco) {
        this.jatEndereco = jatEndereco;
    }




}


