package bean;
// Generated 08/10/2025 16:50:28 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JatProdutos generated by hbm2java
 */
@Entity
@Table(name="jat_produtos"
    ,catalog="db_joao_viana"
)
public class JatProdutos  implements java.io.Serializable {


     private int jatIdProdutos;
     private String jatNome;
     private String jatModelo;
     private double jatValor;
     private String jatTipo;
     private String jatAtivo;
     private Date jatGarantia;


    public JatProdutos() {
    }

	
    public JatProdutos(int jatIdProdutos) {
        this.jatIdProdutos = jatIdProdutos;
    }
    public JatProdutos(int jatIdProdutos, String jatNome, String jatModelo, double jatValor, String jatTipo, String jatAtivo, Date jatGarantia) {
       this.jatIdProdutos = jatIdProdutos;
       this.jatNome = jatNome;
       this.jatModelo = jatModelo;
       this.jatValor = jatValor;
       this.jatTipo = jatTipo;
       this.jatAtivo = jatAtivo;
       this.jatGarantia = jatGarantia;
       
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="jat_id_produtos", unique=true, nullable=false)
    public int getJatIdProdutos() {
        return this.jatIdProdutos;
    }
    
    public void setJatIdProdutos(int jatIdProdutos) {
        this.jatIdProdutos = jatIdProdutos;
    }

    
    @Column(name="jat_nome", length=20)
    public String getJatNome() {
        return this.jatNome;
    }
    
    public void setJatNome(String jatNome) {
        this.jatNome = jatNome;
    }

    
    @Column(name="jat_modelo", length=40)
    public String getJatModelo() {
        return this.jatModelo;
    }
    
    public void setJatModelo(String jatModelo) {
        this.jatModelo = jatModelo;
    }

    
    @Column(name="jat_valor", precision=7)
    public double getJatValor() {
        return this.jatValor;
    }
    
    public void setJatValor(double jatValor) {
        this.jatValor = jatValor;
    }

    
    @Column(name="jat_tipo", length=30)
    public String getJatTipo() {
        return this.jatTipo;
    }
    
    public void setJatTipo(String jatTipo) {
        this.jatTipo = jatTipo;
    }

    
    @Column(name="jat_ativo", length=1)
    public String getJatAtivo() {
        return this.jatAtivo;
    }
    
    public void setJatAtivo(String jatAtivo) {
        this.jatAtivo = jatAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_garantia", length=10)
    public Date getJatGarantia() {
        return this.jatGarantia;
    }
    
    public void setJatGarantia(Date jatGarantia) {
        this.jatGarantia = jatGarantia;
    }

    @Override
    public String toString() {
        return this.jatNome;
    }
    
    @Override
    public boolean equals( Object object){
        if(object instanceof JatProdutos) {
            JatProdutos jatProdutos = (JatProdutos)object;
            if(this.getJatIdProdutos()== jatProdutos.getJatIdProdutos()){
                return true;
            }
    }

        return false;
    }

}


