package bean;
// Generated 08/10/2025 15:35:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JatProdutos generated by hbm2java
 */
@Entity
@Table(name="jat_produtos"
    ,catalog="db_joao_viana"
)
public class JatProdutos  implements java.io.Serializable {


     private int jatIdProdutos;
     private String jatNome;
     private String jatModelo;
     private BigDecimal jatValor;
     private String jatTipo;
     private Character jatAtivo;
     private Date jatGarantia;
     private Set jatVendasProdutoses = new HashSet(0);

    public JatProdutos() {
    }

	
    public JatProdutos(int jatIdProdutos) {
        this.jatIdProdutos = jatIdProdutos;
    }
    public JatProdutos(int jatIdProdutos, String jatNome, String jatModelo, BigDecimal jatValor, String jatTipo, Character jatAtivo, Date jatGarantia, Set jatVendasProdutoses) {
       this.jatIdProdutos = jatIdProdutos;
       this.jatNome = jatNome;
       this.jatModelo = jatModelo;
       this.jatValor = jatValor;
       this.jatTipo = jatTipo;
       this.jatAtivo = jatAtivo;
       this.jatGarantia = jatGarantia;
       this.jatVendasProdutoses = jatVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="jat_id_produtos", unique=true, nullable=false)
    public int getJatIdProdutos() {
        return this.jatIdProdutos;
    }
    
    public void setJatIdProdutos(int jatIdProdutos) {
        this.jatIdProdutos = jatIdProdutos;
    }

    
    @Column(name="jat_nome", length=20)
    public String getJatNome() {
        return this.jatNome;
    }
    
    public void setJatNome(String jatNome) {
        this.jatNome = jatNome;
    }

    
    @Column(name="jat_modelo", length=40)
    public String getJatModelo() {
        return this.jatModelo;
    }
    
    public void setJatModelo(String jatModelo) {
        this.jatModelo = jatModelo;
    }

    
    @Column(name="jat_valor", precision=7)
    public BigDecimal getJatValor() {
        return this.jatValor;
    }
    
    public void setJatValor(BigDecimal jatValor) {
        this.jatValor = jatValor;
    }

    
    @Column(name="jat_tipo", length=30)
    public String getJatTipo() {
        return this.jatTipo;
    }
    
    public void setJatTipo(String jatTipo) {
        this.jatTipo = jatTipo;
    }

    
    @Column(name="jat_ativo", length=1)
    public Character getJatAtivo() {
        return this.jatAtivo;
    }
    
    public void setJatAtivo(Character jatAtivo) {
        this.jatAtivo = jatAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_garantia", length=10)
    public Date getJatGarantia() {
        return this.jatGarantia;
    }
    
    public void setJatGarantia(Date jatGarantia) {
        this.jatGarantia = jatGarantia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jatProdutos")
    public Set getJatVendasProdutoses() {
        return this.jatVendasProdutoses;
    }
    
    public void setJatVendasProdutoses(Set jatVendasProdutoses) {
        this.jatVendasProdutoses = jatVendasProdutoses;
    }




}


