package bean;
// Generated 08/10/2025 15:35:01 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JatUsuarios generated by hbm2java
 */
@Entity
@Table(name="jat_usuarios"
    ,catalog="db_joao_viana"
)
public class JatUsuarios  implements java.io.Serializable {


     private int jatIdUsuarios;
     private String jatNome;
     private String jatApelido;
     private String jatCpf;
     private Date jatDataDeNascimento;
     private String jatSenha;
     private String jatAtivo;

    public JatUsuarios() {
    }

	
    public JatUsuarios(int jatIdUsuarios) {
        this.jatIdUsuarios = jatIdUsuarios;
    }
    public JatUsuarios(int jatIdUsuarios, String jatNome, String jatApelido, String jatCpf, Date jatDataDeNascimento, String jatSenha, String jatAtivo) {
       this.jatIdUsuarios = jatIdUsuarios;
       this.jatNome = jatNome;
       this.jatApelido = jatApelido;
       this.jatCpf = jatCpf;
       this.jatDataDeNascimento = jatDataDeNascimento;
       this.jatSenha = jatSenha;
       this.jatAtivo = jatAtivo;
    }
   
     @Id 

    
    @Column(name="jat_id_usuarios", unique=true, nullable=false)
    public int getJatIdUsuarios() {
        return this.jatIdUsuarios;
    }
    
    public void setJatIdUsuarios(int jatIdUsuarios) {
        this.jatIdUsuarios = jatIdUsuarios;
    }

    
    @Column(name="jat_nome", length=50)
    public String getJatNome() {
        return this.jatNome;
    }
    
    public void setJatNome(String jatNome) {
        this.jatNome = jatNome;
    }

    
    @Column(name="jat_apelido", length=25)
    public String getJatApelido() {
        return this.jatApelido;
    }
    
    public void setJatApelido(String jatApelido) {
        this.jatApelido = jatApelido;
    }

    
    @Column(name="jat_cpf", length=14)
    public String getJatCpf() {
        return this.jatCpf;
    }
    
    public void setJatCpf(String jatCpf) {
        this.jatCpf = jatCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_dataDeNascimento", length=10)
    public Date getJatDataDeNascimento() {
        return this.jatDataDeNascimento;
    }
    
    public void setJatDataDeNascimento(Date jatDataDeNascimento) {
        this.jatDataDeNascimento = jatDataDeNascimento;
    }

    
    @Column(name="jat_senha", length=20)
    public String getJatSenha() {
        return this.jatSenha;
    }
    
    public void setJatSenha(String jatSenha) {
        this.jatSenha = jatSenha;
    }

    
    @Column(name="jat_ativo", length=10)
    public String getJatAtivo() {
        return this.jatAtivo;
    }
    
    public void setJatAtivo(String jatAtivo) {
        this.jatAtivo = jatAtivo;
    }




}


