package bean;
// Generated 08/10/2025 16:50:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JatVendas generated by hbm2java
 */
@Entity
@Table(name="jat_vendas"
    ,catalog="db_joao_viana"
)
public class JatVendas  implements java.io.Serializable {


     private int jatIdVendas;
     private JatClientes jatClientes;
     private Date jatDataVenda;
     private String jatTipoVenda;
     private double jatValorVenda;
     private String jatFormaPagamento;
    

    public JatVendas() {
    }

	
    public JatVendas(int jatIdVendas) {
        this.jatIdVendas = jatIdVendas;
    }
    public JatVendas(int jatIdVendas, JatClientes jatClientes, Date jatDataVenda, String jatTipoVenda, double jatValorVenda, String jatFormaPagamento) {
       this.jatIdVendas = jatIdVendas;
       this.jatClientes = jatClientes;
       this.jatDataVenda = jatDataVenda;
       this.jatTipoVenda = jatTipoVenda;
       this.jatValorVenda = jatValorVenda;
       this.jatFormaPagamento = jatFormaPagamento;
    
    }
   
     @Id 

    
    @Column(name="jat_id_vendas", unique=true, nullable=false)
    public int getJatIdVendas() {
        return this.jatIdVendas;
    }
    
    public void setJatIdVendas(int jatIdVendas) {
        this.jatIdVendas = jatIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jat_fk_id_clientes")
    public JatClientes getJatClientes() {
        return this.jatClientes;
    }
    
    public void setJatClientes(JatClientes jatClientes) {
        this.jatClientes = jatClientes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jat_data_venda", length=10)
    public Date getJatDataVenda() {
        return this.jatDataVenda;
    }
    
    public void setJatDataVenda(Date jatDataVenda) {
        this.jatDataVenda = jatDataVenda;
    }

    
    @Column(name="jat_tipo_venda", length=20)
    public String getJatTipoVenda() {
        return this.jatTipoVenda;
    }
    
    public void setJatTipoVenda(String jatTipoVenda) {
        this.jatTipoVenda = jatTipoVenda;
    }

    
    @Column(name="jat_valor_venda", precision=7)
    public double getJatValorVenda() {
        return this.jatValorVenda;
    }
    
    public void setJatValorVenda(double jatValorVenda) {
        this.jatValorVenda = jatValorVenda;
    }

    
    @Column(name="jat_forma_pagamento", length=10)
    public String getJatFormaPagamento() {
        return this.jatFormaPagamento;
    }
    
    public void setJatFormaPagamento(String jatFormaPagamento) {
        this.jatFormaPagamento = jatFormaPagamento;
    }


}


