package bean;
// Generated 08/10/2025 16:50:28 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JatVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="jat_vendas_produtos"
    ,catalog="db_joao_viana"
)
public class JatVendasProdutos  implements java.io.Serializable {


     private int jatIdVendasProdutos;
     private JatProdutos jatProdutos;
     private JatVendas jatVendas;
     private int jatQuantidade;
     private double jatValorUnitario;

    public JatVendasProdutos() {
    }

	
    public JatVendasProdutos(int jatIdVendasProdutos) {
        this.jatIdVendasProdutos = jatIdVendasProdutos;
    }
    public JatVendasProdutos(int jatIdVendasProdutos, JatProdutos jatProdutos, JatVendas jatVendas, int jatQuantidade, double jatValorUnitario) {
       this.jatIdVendasProdutos = jatIdVendasProdutos;
       this.jatProdutos = jatProdutos;
       this.jatVendas = jatVendas;
       this.jatQuantidade = jatQuantidade;
       this.jatValorUnitario = jatValorUnitario;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY) 
    
    @Column(name="jat_id_vendas_produtos", unique=true, nullable=false)
    public int getJatIdVendasProdutos() {
        return this.jatIdVendasProdutos;
    }
    
    public void setJatIdVendasProdutos(int jatIdVendasProdutos) {
        this.jatIdVendasProdutos = jatIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jat_fk_id_produtos")
    public JatProdutos getJatProdutos() {
        return this.jatProdutos;
    }
    
    public void setJatProdutos(JatProdutos jatProdutos) {
        this.jatProdutos = jatProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jat_fk_id_vendas")
    public JatVendas getJatVendas() {
        return this.jatVendas;
    }
    
    public void setJatVendas(JatVendas jatVendas) {
        this.jatVendas = jatVendas;
    }

    
    @Column(name="jat_quantidade")
    public int getJatQuantidade() {
        return this.jatQuantidade;
    }
    
    public void setJatQuantidade(int jatQuantidade) {
        this.jatQuantidade = jatQuantidade;
    }

    
    @Column(name="jat_valor_unitario", precision=7)
    public double getJatValorUnitario() {
        return this.jatValorUnitario;
    }
    
    public void setJatValorUnitario(double jatValorUnitario) {
        this.jatValorUnitario = jatValorUnitario;
    }




}


